### ISSUE TITLE
Problems about Using  more than one GPU to Train

### ISSUE THREAD

**Issue by xiazhi1** [facebookresearch/robust-dynrf#1]
Hi,Thanks for awesome work.
I have some problem when I run it on more GPU.  I want to know if your code supports it

**Comment by alex04072000** [comment]
Thank you so much for being interested in our work! 
Currently, our implementation only supports single GPU training. However, multi-GPU training should be feasible by `torch.nn.DataParallel`.

**Comment by WithFoxSquirrel** [comment]
> Thank you so much for being interested in our work! Currently, our implementation only supports single GPU training. However, multi-GPU training should be feasible by `torch.nn.DataParallel`.

How long does it take to train a model on V100？
