### ISSUE TITLE
No module named 'torch_efficient_distloss'

### ISSUE THREAD

**Issue by WithFoxSquirrel** [facebookresearch/robust-dynrf#11]
Thank you for the great work, When i train the Jumping  scene,  following error occur
```
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from torch_efficient_distloss import (
ModuleNotFoundError: No module named 'torch_efficient_distloss'
```
I can't find the module torch_efficient_distloss

**Comment by balazon** [comment]
I had the same, but fixed it with:
pip install torch_efficient_distloss

**Comment by WithFoxSquirrel** [comment]
> I had the same, but fixed it with: pip install torch_efficient_distloss

It works , thank you!
